/**
 * HR API
 * HR API
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import io.swagger.client.model.InlineResponse200
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object DefaultApi {

  /**
   * Get Users from DB.
   * 
   * Expected answers:
   *   code 200 : InlineResponse200 (OK)
   * 
   * @param firstName Users first name.
   */
  def userGet(firstName: String): ApiRequest[InlineResponse200] =
    ApiRequest[InlineResponse200](ApiMethods.GET, "https://virtserver.swaggerhub.com/Temil/Hr_Temil_1_2/0.1", "/user", "application/json")
      .withQueryParam("first_name", firstName)
      .withSuccessResponse[InlineResponse200](200)
        /**
   * sample
   * 
   * Expected answers:
   *   code 200 :  (OK)
   */
  def userPost(): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "https://virtserver.swaggerhub.com/Temil/Hr_Temil_1_2/0.1", "/user", "application/json")
      .withSuccessResponse[Unit](200)
      

}

